# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-05 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='picture/image.jpg', upload_to='picture/')),
            ],
        ),
    ]
